"""
Django settings for lumen project.

Generated by 'django-admin startproject' using Django 4.2.24.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o arquivo .env que está na raiz do projeto (para DEV)
load_dotenv(BASE_DIR / ".env")

# -------------------------------------------------------------------
# Feature flag para separar DEV e PROD
# -------------------------------------------------------------------
TARGET_ENV = os.getenv("TARGET_ENV", "Dev")
NOT_PROD = not TARGET_ENV.lower().startswith("prod")

if NOT_PROD:
    # ==========================
    # AMBIENTE DE DESENVOLVIMENTO
    # ==========================
    DEBUG = True

    # SECRET_KEY só para DEV
    SECRET_KEY = "django-insecure-vu(658w7!0v3e+ynpd-o8yo3pz%h^-=w!c5lrp#f-*8qg6##^f"

    # Em dev, só localhost
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

    # Banco padrão SQLite em DEV
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    # CSRF em DEV (opcional, mas deixei explícito)
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
    ]

else:
    # ==========================
    # AMBIENTE DE PRODUÇÃO (AZURE)
    # ==========================
    SECRET_KEY = os.getenv("SECRET_KEY")
    DEBUG = os.getenv("DEBUG", "0").lower() in ["true", "t", "1"]

    # Hosts permitidos
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split()

    # --- CSRF_TRUSTED_ORIGINS ---
    # Garante que SEMPRE tenha o domínio da Azure com esquema https://
    default_csrf = [
        "https://lumenproject-bngwcwejdgevhjbt.brazilsouth-01.azurewebsites.net",
    ]
    extra_csrf = os.getenv("CSRF_TRUSTED_ORIGINS", "").split()
    # se tiver algo no App Settings, adiciona
    for origin in extra_csrf:
        if origin and origin not in default_csrf:
            default_csrf.append(origin)
    CSRF_TRUSTED_ORIGINS = default_csrf

    # HTTPS / proxy
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "0").lower() in [
        "true",
        "t",
        "1",
    ]
    if SECURE_SSL_REDIRECT:
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Banco Postgres da Azure
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DBNAME"),
            "HOST": os.environ.get("DBHOST"),
            "USER": os.environ.get("DBUSER"),
            "PASSWORD": os.environ.get("DBPASS"),
            "OPTIONS": {"sslmode": "require"},
        }
    }

# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise logo após SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lumen.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app1.context_processors.flag_progress",
            ],
        },
    },
]

WSGI_APPLICATION = "lumen.wsgi.application"

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------

STATIC_URL = "/static/"

# pasta onde o collectstatic vai juntar os arquivos para produção (Azure)
STATIC_ROOT = BASE_DIR / "staticfiles"

# pasta de arquivos estáticos do projeto (para CSS/JS/imagens)
# só adiciona se a pasta realmente existir (evita o warning no Azure)
STATICFILES_DIRS = []
static_dir = BASE_DIR / "static"
if static_dir.exists():
    STATICFILES_DIRS.append(static_dir)

# WhiteNoise: servir arquivos estáticos comprimidos e versionados em produção
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# -------------------------------------------------------------------
# Default primary key field type
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------------------------------------
# Auth / Login
# -------------------------------------------------------------------

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_URL = "home"

# -------------------------------------------------------------------
# Variáveis de ambiente de IA
# (hoje o ai.py usa OPENAI_API_KEY e GEMINI_API_KEY,
#  então essas daqui são mais para referência geral)
# -------------------------------------------------------------------
OPENAI_KEY = os.getenv("OPENAI_KEY")
GEMINI_KEY = os.getenv("GEMINI_KEY")

# -------------------------------------------------------------------
# Email settings
# -------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")  # senha de app do Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
