# Generated by Django 4.2.24 on 2025-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_artigos_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigos',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artigos',
            name='resumo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
