# Generated by Django 4.2.24 on 2025-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
