# Generated by Django 6.0 on 2025-12-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_notificacao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Leitor', max_length=80)),
                ('texto', models.TextField()),
                ('avatar', models.URLField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app1.artigos')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
