# Generated by Django 6.0 on 2025-12-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fix_comentario_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created_at']},
        ),
    ]
